<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2015 rel. 4 (http://www.altova.com) by M01 (LUSIS) -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://ns.editeur.org/onix/3.0/reference" targetNamespace="http://ns.editeur.org/onix/3.0/reference">
	<wsdl:import namespace="http://ns.editeur.org/onix/3.0/reference" location="ONIX_BookProduct_3.0_reference_strict.xsd"/>
	<wsdl:types/>
	<wsdl:message name="productSender">
		<wsdl:part name="fullProduct" element="tns:Product"/>
	</wsdl:message>
	<wsdl:portType name="codecPortType">
		<wsdl:operation name="sendProduct">
			<wsdl:input message="tns:productSender"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="codecBinding" type="tns:codecPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="sendProduct">
			<soap:operation soapAction="urn:#codecOperation" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="codecService">
		<wsdl:port name="codecPort" binding="tns:codecBinding">
			<soap:address location="http://www.lusis.fr/codec"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
